### ISSUE TITLE
excel xlsx file(koparadigm.xlsx); not supported in latest xlrd(version 2.0.1)

### ISSUE THREAD

**Issue by bernardscumm** [Kyubyong/paradigm#2]
약 4~5시간전에 xlrd 라이브러리의 버전이 1.2.0 에서 2.0.1 로 업데이트되었습니다.
최신 버전의 xlrd 라이브러리를 사용할 경우에 아래와 같은 오류가 발생하여 이슈를 등록합니다.
- xlrd.biffh.XLRDError: Excel xlsx file; not supported

더이상 xlsx 을 지원하지 않는 것으로 보입니다.
- https://pypi.org/project/xlrd/2.0.1/

이미 동작이 검증된 xlrd 버전(1.2.0) 으로 고정을 했으면 하는 의견을 남깁니다.

```
REQUIRED_PACKAGES = [
    'jamo',
    'xlrd==1.2.0',
]
```

**Comment by CLIDragon** [comment]
This is fixed in my pull request: #4.
